#!/usr/bin/env bun
/**
 * Font subsetting build pipeline.
 *
 * Copies pre-subsetted font files from @fontsource packages to public/fonts/
 * and generates src/styles/fonts.css with per-script @font-face declarations.
 *
 * Usage:
 *   bun run subset:fonts
 */

import { mkdir, copyFile, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT_DIR = join(ROOT, 'public', 'fonts');
const CSS_PATH = join(ROOT, 'src', 'styles', 'fonts.css');

interface FontDef {
  package: string;
  family: string;
  weights: number[];
  styles: string[];
  scripts: string[];
  cssFamily?: string;
}

const FONTS: FontDef[] = [
  {
    package: '@fontsource/inter',
    family: 'Inter',
    weights: [400, 500, 700],
    styles: ['normal'],
    scripts: ['latin', 'latin-ext', 'vietnamese', 'cyrillic', 'greek'],
  },
  {
    package: '@fontsource/space-grotesk',
    family: 'Space Grotesk',
    cssFamily: 'Space Grotesk',
    weights: [500, 700],
    styles: ['normal'],
    scripts: ['latin', 'latin-ext', 'vietnamese'],
  },
  {
    package: '@fontsource/jetbrains-mono',
    family: 'JetBrains Mono',
    cssFamily: 'JetBrains Mono',
    weights: [400],
    styles: ['normal'],
    scripts: ['latin', 'latin-ext', 'cyrillic'],
  },
  {
    package: '@fontsource/noto-sans-devanagari',
    family: 'Noto Sans Devanagari',
    cssFamily: 'Noto Sans Devanagari',
    weights: [400, 700],
    styles: ['normal'],
    scripts: ['devanagari'],
  },
  {
    package: '@fontsource/noto-sans-bengali',
    family: 'Noto Sans Bengali',
    cssFamily: 'Noto Sans Bengali',
    weights: [400, 700],
    styles: ['normal'],
    scripts: ['bengali'],
  },
  {
    package: '@fontsource/noto-sans-arabic',
    family: 'Noto Sans Arabic',
    cssFamily: 'Noto Sans Arabic',
    weights: [400, 700],
    styles: ['normal'],
    scripts: ['arabic'],
  },
  {
    package: '@fontsource/noto-sans-hebrew',
    family: 'Noto Sans Hebrew',
    cssFamily: 'Noto Sans Hebrew',
    weights: [400, 700],
    styles: ['normal'],
    scripts: ['hebrew'],
  },
  {
    package: '@fontsource/noto-sans-thai',
    family: 'Noto Sans Thai',
    cssFamily: 'Noto Sans Thai',
    weights: [400, 700],
    styles: ['normal'],
    scripts: ['thai'],
  },
];

async function loadUnicodeRanges(pkg: string): Promise<Record<string, string>> {
  const path = join(ROOT, 'node_modules', pkg, 'unicode.json');
  const content = await import(path, { assert: { type: 'json' } });
  return content.default ?? content;
}

function toKebab(str: string): string {
  return str.toLowerCase().replace(/\s+/g, '-');
}

function toCamel(str: string): string {
  return str.replace(/[-\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));
}

async function main(): Promise<void> {
  if (existsSync(OUT_DIR)) {
    await rm(OUT_DIR, { recursive: true });
  }
  await mkdir(OUT_DIR, { recursive: true });

  const cssBlocks: string[] = [];
  cssBlocks.push('/* Generated by scripts/subset-fonts.ts — do not edit manually */');
  cssBlocks.push('');

  for (const font of FONTS) {
    const pkgDir = join(ROOT, 'node_modules', font.package);
    const filesDir = join(pkgDir, 'files');
    const unicodeRanges = await loadUnicodeRanges(font.package);

    for (const script of font.scripts) {
      const range = unicodeRanges[script];
      if (range == null || range === '') {
        console.warn(`  Skip ${font.family} ${script}: no unicode range`);
        continue;
      }

      for (const weight of font.weights) {
        for (const style of font.styles) {
          const styleSuffix = style === 'italic' ? '-italic' : '-normal';
          const srcName = `${toKebab(font.family)}-${script}-${weight}${styleSuffix}`;
          const srcPath = join(filesDir, `${srcName}.woff2`);

          if (!existsSync(srcPath)) {
            console.warn(`  Missing ${srcName}.woff2 for ${font.package}`);
            continue;
          }

          const outName = `${toKebab(font.cssFamily ?? font.family)}-${script}-${weight}${styleSuffix}.woff2`;
          const outPath = join(OUT_DIR, outName);
          await copyFile(srcPath, outPath);

          const cssFamily = font.cssFamily ?? font.family;
          const cssStyle = style === 'italic' ? 'italic' : 'normal';

          cssBlocks.push(`@font-face {`);
          cssBlocks.push(`  font-family: '${cssFamily}';`);
          cssBlocks.push(`  src: url('/fonts/${outName}') format('woff2');`);
          cssBlocks.push(`  unicode-range: ${range};`);
          cssBlocks.push(`  font-display: swap;`);
          cssBlocks.push(`  font-weight: ${weight};`);
          cssBlocks.push(`  font-style: ${cssStyle};`);
          cssBlocks.push(`}`);
          cssBlocks.push('');

          const { stat } = await import('node:fs/promises');
          const s = await stat(outPath);
          console.log(`  ${outName} → ${s.size} bytes`);
        }
      }
    }
  }

  await writeFile(CSS_PATH, cssBlocks.join('\n'));
  console.log(`\nWrote ${CSS_PATH}`);
  console.log(`Fonts output to ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
